language: go
sudo: required
addons:
  apt:
    packages:
    - docker-ce
install: true
script: true
jobs:
  fast_finish: true
  include:
  - stage: build and push
    script:
    - go get -u github.com/golang/dep/cmd/dep
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - if [ -n "$TRAVIS_TAG" ]; then make TAG=$TRAVIS_TAG; else make; fi
    if: "(NOT type IN (pull_request)) AND (branch = master) OR (tag IS present)"
notifications:
  slack:
    rooms:
      secure: Jpib//uftL3PoHzuE8scV2YRTv5l2wKDU+dN43f4Z/oU1SqhB96f5pB+6NHg3oajA8tDGNqYulpwEJLUHn2fwHw9ZH0qccS8PjnhxgIx6rOWe03vY6rzFhHt5gAQsBM3vhH7pdWHz3jI2KbqJ1GLsyKV2DSCggdy3EJSUeyYVbLDHEPiCxqcPqPiGD/i/RGhxJ8/voFx7GDDO1gGkghh8hcbQemU8wWqyvKeMy1yhglwAzqkrsdzFV+DZQH3z+HEHh+nKHZpm1mPbsouJlFaSnrW9oWnJGAabOhfKlJqcURf0kbzsJJ0E7ggFJqe61kWuHw6nollmcd1YMaAhvhI0f8rHz8TbTBtnGGmjRQvNVKBHzAZuJzN4h4c1EATVfpba5p+UX87RrJ82cxyCcOxQKQQcJlOQPboOpLdjX4ZafLyFqzeKqHrsH6hgR4rMmI+jdNLquXQRVR7hJLsXMNLNGXwabR9hbF5mBu5ebwMuyhFXxLG/+QT9ZY1DVSUbUXjm3PyANSQAh9qtdlaCjM45Mc8Oyy73TIvitr4N3kB5lkP8/gI/Mt+qSjC0dBvTkmUb1ShoalX050XMABtf2tGtbea98GpW+ABuHky/8LL226BkXzMBGwklOAH1zc4/L/fs0HiS1r4YmBghtjap6ZWtUbH1FGRao6gh5cCJDpkyHw=
env:
  global:
    secure: mJuzH8Q9j31MAOLj3116knIX/q6wuCzyiZ6MmBi+j8S4ejI3yiAroqqvHEUr8TSmqgO4rvII+D4MSj4Ji+UoLiXiCrvM1zLi6QvgR+0VE8fGtpKx79mrbvphbehVqPiuDMa/9HQyM6h0M1a63FR78OYdpLDcBVdgJ4Hc37orGwP6sqCnmnlBgah+aHeXrTIFIWUMtmFv+1KSU/FjahWacU5ppAXkuu1c1D11P+oCw2w0P72hdvDqWrOYzeovoetLGanKswHCkWXTTyjhh8x6peeotbNdyIoIC+vdAWpCOMUbUvJFLvTyfK44twNgJ4E468WvK2Hl0QfKXqg8WCeTOKeOF4TqRsLjuf7j6JTQeOoUgGW0lthkuWENtTBDlMf60nOU8P9QfxrXcAondYoD3OZeLwk6q8zgMLsdtDzd0HEpeDy6EcoLSUWc4E6FIb3uKs3cnlC+aqTE82444NIpMctDrTIkMxdJSynRayk06ZGbNI4asVinVLQftUo492+t1XCxqkb0T2canzEizeUf/3ZIyPk+zx3dlpfMmaPJ2tgCL4SsfZvm9crsKlZl+lYwa4wx/oz6H2A3ulaOD03VOWOxYOWaxy3eJJcNulXJFeFkALNLP1AmOZBPuntySNpu+j8LVUIo2lhw95+4VPhmTPM1OhUmMcIewzy/u8VhEX4=
